### ISSUE TITLE
Corrigir erro ao gerar DAGs no Airflow 2.10.0

### ISSUE THREAD

**Issue by augusto-herrmann** [gestaogovbr/Ro-dou#134]
No Airflow 2.10.0, no arquivo `dou_dag_generator.py`, ao gerar as DAGs a partir das configurações, aparece o erro:

```
Broken DAG: [/opt/airflow/dags/ro_dou_src/dou_dag_generator.py]
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dag.py", line 781, in __init__
    validate_instance_args(self, DAG_ARGS_EXPECTED_TYPES)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 68, in validate_instance_args
    raise TypeError(
TypeError: 'tags' has an invalid type <class 'set'> with value {'dou', 'generated_dag'}, expected type is <class 'list'>
```

O erro não acontece no Airflow versão 2.9.1, que é a versão usada nos testes do Ro-DOU.

**Comment by augusto-herrmann** [comment]
Recentemente o modelo de configuração de DAGs foi migrado para o Pydantic (#118) e as tags mudaram de uma `list` para um `set`. Porém o Airflow 2.10 espera receber uma lista.
